# Generated by Django 4.1.7 on 2023-03-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=30)),
                ('origin_x', models.FloatField(default=0.0)),
                ('origin_y', models.FloatField(default=0.0)),
                ('resolution', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=30)),
                ('map_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.mapdata')),
                ('current_x', models.FloatField(default=0.0)),
                ('current_y', models.FloatField(default=0.0)),
                ('current_th', models.FloatField(default=0.0)),
            ],
        ),
    ]
