# Generated by Django 4.1.7 on 2023-04-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='current_th',
        ),
        migrations.AddField(
            model_name='robot',
            name='current_z',
            field=models.FloatField(default=0.0),
        ),
    ]
