# Generated by Django 4.1.7 on 2023-04-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_remove_robot_current_th_robot_current_z'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='current_z',
            new_name='current_th',
        ),
    ]
