FROM ubuntu:jammy

SHELL [ "/bin/bash", "-c" ]

RUN apt-get update && \
 apt -y install apt-transport-https ca-certificates curl software-properties-common && \
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
 add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable" && \
 apt-get -y install docker-ce python3-pip sqlite3

RUN pip install Django \
  channels["daphne"] \
  channels-redis \
  tzdata \
  pyyaml \
  numpy
 
